### ISSUE TITLE
prsten z icc 

### ISSUE THREAD

**Issue by Dezmondstark** [overy/CzechFunCore#102]
http://www.wowhead.com/quest=24815
Nezobrazuje se mi nic ke koupi ale mám nad npc modrej otazník 
rekpu mám exalted 
vůbec nevím co stím 
Dezmondstark

**Comment by overy** [comment]
hm a nemas nahodou uz nejaky ring ? tusim ze jine NPC vevnitr dava ring a dalsi ho pak vylepsuje
