### ISSUE TITLE
Poisony - DMR

### ISSUE THREAD

**Issue by martin-ocasek** [overy/CzechFunCore#12]
Poisony maj dmr  - pvp enve rogue je nehratelnej .. 

// dmr maj pouze proti postavam ktery nejak redukuji trvani poisonu .. ta redukce se asi nejak stackuje nebo co , protoze do frost DK nastackuju vpohode , do holypala nemam sanci nastackovat 5 ...

// nejspis to dela talent http://www.wowhead.com/spell=31823/pure-of-heart a podobne efekty ktere maji redukovat trvani poisonu ... talent se proste stackuje tkaze 5 stacku deadly poisonu na paladinovi s timto talentem me vydrzi sotva sekundu .. chtelo by to disable nebo opravit

**Comment by overy** [comment]
Pravdepodobne zpusobene buglymi channeling spelly, takze fixed
