### ISSUE TITLE
Eliminate the Competition (bugly Q)

### ISSUE THREAD

**Issue by Delsonik** [overy/CzechFunCore#18]
Quest, kde je za potrebi zabit 4 pandrlaky pro repku s Ebon Blade (http://www.wowwiki.com/Quest:Eliminate_the_Competition) z kterych konretne (http://www.wowwiki.com/Efrem_the_Faithful) je neutral a nejde na nej utocit, tim padem nesplnitelny Q....

**Comment by overy** [comment]
fixed
