### ISSUE TITLE
Špatné emblémy

### ISSUE THREAD

**Issue by LeetyP** [overy/CzechFunCore#22]
Sack of Frosty Treasures obsahuje 2-3 Emblem of Conquest namísto 5 Emblem of Frost
http://old.wowhead.com/item=52006#contains

Cache of the Dramwalker obsahuje Emblem of Conquest namísto Emblem of Frost (množství EoF má odpovídat zabitému bossovi)
http://www.wowhead.com/object=201959

V celém ToC10HC padají pravěpodobně EoC namísto EoT (z beastů 10Hc padly pouze Conquesty)
http://www.wowhead.com/zone=4722

**Comment by overy** [comment]
1. Fixed
2. Fixed (nejsem si jistý)
3. zůstane tak jak je 

Samozřejmě after restart

**Comment by LeetyP** [comment]
Proč máš v plánu nechat o tier slabší embly v o třídu silnějším raidu? :)

**Comment by overy** [comment]
Jo my bad, myslel sem že mluvíš o 5tce, psal sem to v rychlosti ... reopen

**Comment by LeetyP** [comment]
Sack of Frosty Treasures dropuje po otevření pouze 2-3 EoF, namísto pěti jak má

**Comment by overy** [comment]
fixed
