### ISSUE TITLE
Scarlet monastery: The Graveyard

### ISSUE THREAD

**Issue by Belialus** [overy/CzechFunCore#24]
Nejde vstoupit do instance.

**Comment by overy** [comment]
co to pise ?

**Comment by pkrupicka** [comment]
Nic, projdu portálem a nic se nestane.

**Comment by LeetyP** [comment]
Jakoby tam port do instance úplně chyběl

**Comment by overy** [comment]
jj no nema to areatrigger teleport, bouzel netusim jak se s tim pracuje rsp jak to pridat, vim kam ale nevim udaje :X

**Comment by Dessus** [comment]
Má DB: 
Nevim kterou Ove máš, možná do toho budeš muset hodit jeste acces_id s hodnotou 0 (pokud tam teda neni zapotrebi nejakej q .. ted nevim) .. koukal jsem se na tc info kde uz ten sloupek maj, nevim jak starou db máš ...

DELETE FROM `world`.`areatrigger_teleport` WHERE `areatrigger_teleport`.`id` = 45;

INSERT INTO `world`.`areatrigger_teleport` (`id` ,`name` ,`target_map` ,`target_position_x` ,`target_position_y` ,`target_position_z` ,`target_orientation`)
VALUES 
('45', 'Scarlet Monastery - Graveyard (Entrance)', '189', '1688.99', '1053.48', '18.6775', '0.00117');

**Comment by overy** [comment]
Jo diky, u nas to chybelo mel sem nejakou divnou DB ... Closed fixed
