### ISSUE TITLE
[Vault of Archavon] - Emblems

### ISSUE THREAD

**Issue by LeetyP** [overy/CzechFunCore#29]
http://www.wowhead.com/npc=31125 Archavon
http://www.wowhead.com/npc=33993 Emalon
http://www.wowhead.com/npc=35013 Kolaron
http://www.wowhead.com/npc=38433 Tovaron

Archavon, Kolaron a Tovaron dropují 2-3 Conquesty. Emalon nebyl zabit, ale pravděpodobně dropuje také Conquest.

Přičemž Archavon, Emalon a Kolaron mají dropovat EoT (offi 2)
Tovaron EoF (offi 2)

Add pod čarou: byl by možný lehký enhance (boost) lootu? Z obří tabulky ve které jsou všechny tier sety a některé pve kusy dropnou vždy dva itemy jako na offi a zatím jsme to vždy (z pěti runů) až na jeden pvp item který šel do off specu disenchantnuli protože padly kraviny / itemy které někdo měl / nikdo neupotřebil

**Comment by overy** [comment]
Fixed
