### ISSUE TITLE
[Vault of Archavon] - Alliance - vchod

### ISSUE THREAD

**Issue by LeetyP** [overy/CzechFunCore#30]
Protože je WG vyplé a aktuálně hrad vlastní horda, neexistuje způsob jak dostat alianci do instance bez použití bugů / horďáckého locka

**Comment by overy** [comment]
nepustí je to portálem nebo tam je jiný problém ?

**Comment by Lucr3cia** [comment]
portál funguje jen pro hordu, protože má WG, stačí smazat bránu

**Comment by overy** [comment]
nebo pridat to teleportera moznost portu, je to effektivnejsi nez mazat neco co je vlastne potreba do budoucna.

EDIT: Po restartu přidán port.
