### ISSUE TITLE
[ICC] - Sister Svalna

### ISSUE THREAD

**Issue by LeetyP** [overy/CzechFunCore#31]
Tento miniboss nedropuje 1 Emblem of Frost jak by měl

http://www.wowhead.com/npc=37126

QUOTE Wowhead
Sister Svalna is a Val'kyr mini-boss in the room before the first boss of the Frostwing Halls, Valithria Dreamwalker. 
Kill the trash up to her, which is essentially a gauntlet that you fight with other crusaders. As you are doing this, she will kill your crusader helpers. 
The fight with her is simple, and much akin to the High Warlord Naj'entus encounter in Black Temple, where she will throw her spear at a player in the raid, immobilizing the player. Another player must them loot the spear and throw the spear back at her when she tosses up her immunity bubble. A few times throughout the fight she will resurrect the crusaders she killed. They do not have much health and are easily tanked and spanked. 
Rinse and repeat using the spear to break the bubble and you have yourself a mini boss downed!
In ten man she dropped approx. ~75g and one Emblem of Frost.

**Comment by overy** [comment]
Opraveno po restartu.

**Comment by overy** [comment]
Musim ji udelat zvlast lootid takze reopen.

**Comment by overy** [comment]
fixed
