### ISSUE TITLE
[Wintergrasp] Auto Dismount

### ISSUE THREAD

**Issue by Lucr3cia** [overy/CzechFunCore#32]
WG od patche 3.2.0 nemá dávat nebuff  Restricted Flight Area, který po 10 sekundách dismountne a dá padák.  Tento debuff se nahazuje jen v případě letíme-li moc nízko při započnutém boji.

Viz. http://www.wowhead.com/zone=4197/wintergrasp#comments

With the 3.2 patch, you can fly in Wintergrasp, so long as there is not a battle going on. If there is a battle going, you can fly over Wintergrasp, but if you fly too low, you'll be warned with a Restricted Flight Area debuff. Climbing back to a safe altitude will remove the debuff.

**Comment by Pauli707** [comment]
Jo taky bych prosil o zrušení Dismountu ve WG. Myslím, že by se ulevilo dost lidem na serveru.

**Comment by overy** [comment]
zrušeno
