### ISSUE TITLE
[Shaman] Grounding Totem

### ISSUE THREAD

**Issue by Lucr3cia** [overy/CzechFunCore#35]
Totem: http://www.wowhead.com/spell=8177

Absolutně nefunguje proti jedné jediné classe.......Retri Paladin, všechny jeho homosexuální spelly to počítá snad jako super insane a místo do totemu jdou do mě....
Testoval jsem: 
- Hammer of Wrath - použitelný pod 20% hp, dmg šel do mě a totem stál
- Judgement of Justice - Dmg jsem dostal z Judgementu i Sealu, totem zmizel
- Divine Storm - Dmg jsem dostal, totem zmizel

Spelly ostatních class fungují bezchybně, prosil bych fix totemu nebo smazání paladinů, vřele děkuji předem.

**Comment by Pauli707** [comment]
Zrovna u Retardinů by bylo potřeba takové věci fixnout že? Je to sice drobnost, ale závažná. Lepší zpráva pro tebe je, že to na serveru nikdo za retri pořádně nedává =D
