### ISSUE TITLE
[Reputace] Ravenholdt

### ISSUE THREAD

**Issue by Lucr3cia** [overy/CzechFunCore#36]
http://www.wowhead.com/quest=8249

quest funguje jen rogunám, proto bych byl rád za zrušení class omezení.

Since the quests that give Ravenholdt reputation are mostly for rogues, this faction is more or less rogue-only.
The repeatable Junkboxes Needed quest is obtainable by non-rogues, but the junkboxes themselves can only be obtained by pickpocketing.

**Comment by overy** [comment]
fixed
