### ISSUE TITLE
[Quest] Quel'delar

### ISSUE THREAD

**Issue by Lucr3cia** [overy/CzechFunCore#37]
Díky, že jsi spawnul QD pod Argent Tournament, ale mohl by jsi ho prosím spawnout s tímto questem (http://www.wowhead.com/quest=24480) v quest logu? Když ten quest mám, tak se ten imp buguje do jiné fáze a resetuje....takže nejde zabít

Teď sme ho s lolqem z fáze vytáhli, splnila se první část questu:  Bring Quel'Delar to Halls of Reflection, ale nespadl z něj quest item...http://www.wowhead.com/item=50254

viz. http://www.imghosting.cz/images/18Q_D.jpg

**Comment by overy** [comment]
fixed v další revizi

**Comment by overy** [comment]
temp fix aplikován ...
