### ISSUE TITLE
(Mage) Nejde bonus u t10 

### ISSUE THREAD

**Issue by Pospa** [overy/CzechFunCore#4]
U T10 pro mage nefunguje 2 bonus (http://www.wowhead.com/item=50275) 12% haste po skončení hot streak, brain freeze ... a jestli by to slo tak jesli by jsi mi mohl vratit těch 60 eof, protože ty ramena jsou slabší než mám pro mě to jsou vyhozene eof .

**Comment by ZechY** [comment]
Mage T10 bonus opraven, někdo testněte...

**Comment by ZechY** [comment]
Otestováno, funkční...

**Comment by overy** [comment]
to si nahodil revizi odsud ? ja jen ze tahle je stara

**Comment by ZechY** [comment]
Ne nenahazoval, upravoval jsem to ručně.

**Comment by overy** [comment]
fixed
