### ISSUE TITLE
[ICC] Valanar - Empowered shock vortex

### ISSUE THREAD

**Issue by LeetyP** [overy/CzechFunCore#40]
Jak to má být:
Když má Valanar buff, castí empo shock vortex, to znamená pokud jsou dodrženy rozestupy 10y tak každý dostane 5k fyzický a to je vše.

Jak to je:
Jenže tady můžete stát od sebe třeba napříč světem jenže i když dodržíte rozestupy tak dostanete 5k + kickback. Přičemž kickback máte dostat pouze pokud u někoho jste blíže než 10y

Vypadá to že to není problém, ale je to hodně velkej problém

**Comment by overy** [comment]
http://www.wowwiki.com/Blood_Prince_Council
Empowered Shock Vortex 50,000 yd range — Creates force vortices on all nearby enemies, inflicting 5000 Physical damage and knocking enemies with ~12 yds of the the target away. 4.5 second cast. (from 10man difficulty)
how it should work:
- the spell is cast on ALL raid members but it should only affect (give dmg and knockback) the raid members that are within ~12yards of eachother (not 12yrds from the boss)
  Atm it knocks back and gives dmg to pretty much everyone in the raid
