### ISSUE TITLE
[ICC] Keleseth + Empowered Shadow Lance + Dark Nucleus

### ISSUE THREAD

**Issue by LeetyP** [overy/CzechFunCore#41]
Pokud Keleseth dostane Empower buff jako druhý tak prostě není dost Nucelů na to aby tank přežil aspoň první lance (pokud dostane Keleseth empower jako druhý, je spawnutý právě jeden nucleus, takže tank místo 80k koupí za 60k, nazdar (a to se musí haluzí spawnout blízko aby se k nucleu stihlo dojít))

Pokud Keleseth dostane Empower buff jako třetí prostě není dost Nucleů na to aby tank přežil aspoň druhý lance (pokud dostane Keleseth Empower jako třetí, jsou spawnuté právě 2-3 nucleusy, takže je to jen o posraném štěstí kam se spawnou, protože se prostě nedá chodit přez celou místnost, a i když máte štěstí, tak 3 jsou pořád málo . . .)

**Comment by overy** [comment]
No a jak je to řešené na offi ?

**Comment by LeetyP** [comment]
http://www.wowwiki.com/Blood_Prince_Council

roll down

Hotfix (2010-01-22):
"The first Shadow Resonance should appear earlier in the fight, which will allow the Keleseth tank to have more orbs on him or her if Keleseth is empowered second instead of third. We didn't want which Blood Prince was empowered second to be a major element of the difficulty in the fight."

**Comment by overy** [comment]
dal jsem spawn Dark Nucleus na random hrace ... udajne se nektere spawnovali pod texturu takze by jich melo byt vice nyni
