### ISSUE TITLE
Frost DK - Threat of Thassarian

### ISSUE THREAD

**Issue by Strepin** [overy/CzechFunCore#42]
Jak jsem již jednou postoval na minulém bug reportu, Threat of Thassarian je buglý ve smyslu opakování striku druhou zbraní, místo jen dávání dmg druhou zbraní... Projevuje se to zde na Death Striku, který healí DK za 5% max hp za každou aktivní disease na cíli. Bug přichází na scénu při healu, protože takhle se DK healne 2x. Možným řešením je zakázat tuto kombinaci, alespoň dočasně, protože takto buglý Death Strike má vyšší heal output, než Blood talentnutý Death Strike.

**Comment by Pauli707** [comment]
Super, že si to sem napsal. Konečně se to snad opravý. Akorát pak všichni nadávaj.

**Comment by LeetyP** [comment]
Ano, a tuto chybu nahlásím až po čtvrt roce dojení všeho možného tímto způsobem, je super že tě někdo tímto bugem zabil / získal něco co mu závidíš a aby jsi mu zkazil radost při dalším bugování tak jsi to nahlásil, dobrá práce

**Comment by overy** [comment]
TODO: Some people said that it must heal 10% from main hand and 5% from the offhand to match the heal from blood and UH specs, others says its just 5% from main and 5% from off.

**Comment by LeetyP** [comment]
"to match the heal from blood and UH"     ???

To si dělá nějakej týpek prdel? U DKčka jde právě přesně o to že frost nemá takový healy jako blood, takže proč si vymýšlet naprosto novou mechaniku nebo vedlejší efekt který zvětší healy frostu na úroveň bloodu . . . (mě si nevšímejte, jsem jen cataclysm hráč a moje informace jsou neaktuální)

**Comment by overy** [comment]
no prave chtelo by to nejake "potvrzene" informace :X

**Comment by LeetyP** [comment]
Já nevím, zkoušíš si při těch pokusech o fix pročíst aspoň ty posrané tooltipy nebo to končíš u toho "ah, on je op, to je na mě moc op, necháme to tak"

**Comment by overy** [comment]
až na to že já ty fixy nedělám...

**Comment by LeetyP** [comment]
Dobře pane "Deal with it", kdyby jsi to četl tak vyvineš základní snahu s google slovníkem a zjistíš že Threat of Thassarian je buglý, daleko lepší je zkoušet to dávat do pořádku podle toho co ti řekne hra (95% správnost) než se chytat vyjímek, mě naprosto uchází proč je zde od tebe postnuté to "TODO", proč se ty, bůh všeho možného staráš o nějaké "Some ppl said that" když jsi vždycky jel přesně podle toho co spell psal aniž by tě zajímalo co říkají ostatní. Najednou všem neuvěřitelně nasloucháš a už jen přemýšlení nad píčovinama typu "Some ppl said that" se okrádáš o čas

OT: Potom si prosím nevymýšlej, nikdy jsem netvrdil že ty fixy děláš . . .

**Comment by overy** [comment]
to TODO byl post jednoho deva ne můj vymysl, a ja opravdu nevim jak to ma fungovat

**Comment by Pauli707** [comment]
Můžu se zeptatta, jestli je to už opravene? Jinak to má fungovat tak, ze Threat of Thassarian funguje na double DMG, ale ne na zopakování spellu. Ove prosim tě naverbuj někoho ať s tim hnou. 
                                                                                                                               Dik Bride =)

**Comment by overy** [comment]
tenhle bug stale je ... a co chapu tak je bug jen u death striku 

ono sehnat developery neni lehke ... nepohrdnu kdyz se to naucis a budes mi delat deva ...

**Comment by LeetyP** [comment]
Džízs fuking krist, není to double dmg, jen dodatečný dmg z off-handy, a ano, opravdu to omg nemá healovat 2x tolik x_o
