### ISSUE TITLE
Brewfest

### ISSUE THREAD

**Issue by Kerygen** [overy/CzechFunCore#44]
Mam problem z jednoho questu Catch the Wild Wolpertinger!, puvodne jsem mel chitat ty rohate zajice ale ta sit se objevila na me a nemohu kouzlit ani jakkoli bojovat. Vymazal jsem pri rlg cache nechal se zabit nic zatim nepomohlo ani teleportace pres HC. Nick postavy je Kerygen (80lvl, Human, Paladin) .

**Comment by overy** [comment]
napis ingame ticket poresime to pres unaura all

**Comment by LeetyP** [comment]
Lal, stejný problém tu byl i minulý rok

**Comment by overy** [comment]
fixed a dalsi questy kolem tohodle eventu
