### ISSUE TITLE
DK-Unholy

### ISSUE THREAD

**Issue by Se7eNX** [overy/CzechFunCore#5]
Nefunguje Ebon Plaguebringer(http://www.wowhead.com/spell=51160)
-neobnovuje se, další je Unholy blight(http://www.wowhead.com/spell=49194)-nedává dmg taký jaký má dává asi 32dmg a to seš rád...

**Comment by Dessus** [comment]
- Co se unholy blightu týče, dle mě to tedá má dávat 10% dmg z coilu, přičemž se ten dmg rozdělí do 10 sekund ... Zakže coilu za 3k by to tak odpovídalo ...

**Comment by Delsonik** [comment]
Unholy blight jede na 100% jak ma... a toho EP vyskousim...

**Comment by overy** [comment]
co teda ten ebon plaguebringer? at vim jestli closed ci ne

**Comment by Lucr3cia** [comment]
Unholy Blight taky nefunguje, stejně jako všechny ostatní dotky z talentu na stejné bázi (Piercing shots, ignite, deep wounds) DMG má stackovat z každýho death coilu a dmg dotky je navýšen po dobu prvního dmge, je to těžké na pochopení i vysvětlení....prostě dám 2x DC za 3k v rozmezí 5 sekund prvních 5 sekund tedy tiká dotka za 30 ale dalších 5 sekund za 60 díky navýšení druhým coilem, po 5 sekundách spadne dmg prvního coilu a dotka tiká dále za 30

**Comment by overy** [comment]
Co sem cetl tak ignite a deep wounds by melo byt funkcni ale to jen btw ...
