### ISSUE TITLE
[Shaman] Enchanty

### ISSUE THREAD

**Issue by Lucr3cia** [overy/CzechFunCore#50]
Takže...

-Při Storm Striku (main hand + offhand utok) se připočítavá jen main-hand enchant (tedy windfury)...
-Pří Lava Lashi (off hand ůtok) procuje windfury (tedy enchant na main handě)
-Při combatu neprocuje ani jeden z enchantů ze spellů (Storm Strike + Lava Lash)
-Mimo combat nastává situace bodu 1 a 2
- V praxi to výpadá tak, že enchanty procují jen z auto attacku, což vysvetluje brutálně malý DPS output u enha shamana v PVE (a Damage done output v PVP)

**Comment by overy** [comment]
Jestli ovládáš AJ můžes to postnou na TC jelikož to tam nevídím jako revizi uveď a620a763a96425d10dd8ea7ae58703048ed2ee54 1 parent 80720358f0
a DB: TDB DB 

Boužel spelly opravovat neumím takže s tím asi moc nepohnu

**Comment by Lucr3cia** [comment]
WINDFURY (main hand) + FLAMETONGUE WEAPON (offhand)

When Out of combat:

-If Storm strike lands (main hand + offhand attack) it counts in only main hand enchant (windfury) however Flametongue weapon has 100% chance to proc from offhand attacks and it doesn't even land
-If Lava Lash lands (off hand attack only) it just makes dmg of that ability and has a chance to proc Windfury (main hand enchant) but Flametongue doesn't proc again.

While In Combat:
- Both enchants won't proc from abilities so the only way to proc is auto attack 

This bug is huge dps lose for PVE and it makes enhancement shaman useless for PVP.

**Comment by Chronos6664** [comment]
pôvodný report -> https://github.com/SpojkaWoW/Spojka-WoW/issues/224 
lucrecia, nabudúce linkuj keď už kopíruješ ;)

**Comment by Lucr3cia** [comment]
myslíš že na spojce to někdo přepošle dál? Takto je o tom na TC alespoň zmínka, tak můžeš děkovat že to bylo přeloženo a přeposláno

**Comment by Chronos6664** [comment]
však dobre, ja ti len hovorím, že keď to nie je tvoj report a ani si to netestoval tak linkuj ... neprosil som nikoho aby to dával na TC .. keby som to moc chcel tak to tam dám :D

**Comment by Lucr3cia** [comment]
ja to testoval na druhem serveru (czechfun), a problém je úplně stejnej, jen bych na otázku: Proč enha točí tak malé DP nedošel sám....

**Comment by Chronos6664** [comment]
zas tak málo netočí :) 4/5 T10  trinkety low -> pyrite infuser a shard of crystal heart a v 25kach 11k vytočím .. len to nevieš ;) nehovorím že to nie je stráta dps .. to určite je ale to je iba jedna z dvoch chybyčiek krásy .. druhá že necrituje fire nova a totemy .. nič iné bugnuté nie je, iba to treba vedieť točiť
