### ISSUE TITLE
succuba

### ISSUE THREAD

**Issue by martin-ocasek** [overy/CzechFunCore#51]
nejde controlovat ... casti i pres blind + pokud dostane kick casti okamzite znova, ikdyz by 5 sec nemela castit ( to stejne s cs a dalsima interuptama)

chtelo by to fik / disable, s rogunou je nemozne zabit locka, protoze jen na cloak ho nezergnu.

**Comment by overy** [comment]
tohle je problém celkově všech creatur ... jaksi nemají vůbec nějaké ovlivnění na 5sec interupt a podobné efekty

**Comment by martin-ocasek** [comment]
to ze casti pres blind by nejak neslo ovlivnit ? neni to interupt ale disorient.
