### ISSUE TITLE
Sacred Cleansing

### ISSUE THREAD

**Issue by martin-ocasek** [overy/CzechFunCore#52]
Nejde tento talent u holy paladina .. nechapu proc, normalne fungoval akorat problem byl v bugu cleanse ktery uz take funguje jak ma.

**Comment by overy** [comment]
je v disables kvuli bugu co tam byl a jeste zustal pokud vim ... je povoleny pouze rank 1 ...

**Comment by martin-ocasek** [comment]
o jaky bug se jedna ? bugnute bylo to ze slo cleansovat i pri buffu , takze to clovek mohl mit skoro porad. . ted uz jdou dispelovat jen debuffy. takze to tolik neprocuje

**Comment by overy** [comment]
vim ze dastan cosik rikal ze ten debuff si mel porad na sobe ...

**Comment by martin-ocasek** [comment]
jasne .. mohls pouzivat cleanse ikdyzs na sobe nemel zadny debuff = porad spamovals a mels to permanentne, coz uz ted nejde, ted uz jde dispelovat jen kdyz ma tareget nejaky debuff.

**Comment by overy** [comment]
odebral jsem to z disables
