### ISSUE TITLE
WF ramena

### ISSUE THREAD

**Issue by martin-ocasek** [overy/CzechFunCore#55]
jsou zase za trojky.
chtělo by to přehodit na 2k50 rat a 2v2 jak před revkou.

**Comment by Dessus** [comment]
UPDATE npc_vendor SET `ExtendedCost` =2364 WHERE `ExtendedCost` =2948;

**Comment by overy** [comment]
hm 48 zaznamu zmeneno tak se uvidi po restartu :X
