### ISSUE TITLE
T10  4/5 Set bonus

### ISSUE THREAD

**Issue by Pakluc** [overy/CzechFunCore#57]
Set bonus T10 4/5 proste nefunguje vobec. (13% pridanie 3CP po pouziti finishing moves)

**Comment by Strepin** [comment]
Měl bys přihodit pár wowhead odkazů, zprvu jsem nevěděl, co myslíš. Testoval jsi to nějak?

**Comment by Pakluc** [comment]
Tak set bonus ktory som napisal maju len Roguny "13% add 3CP na target pri pouziti finishing moves a to napriklad Eviscerate alebo Envenom...atd... netreba ti nato ziadny wowhead link ale tak 

->  http://www.wowhead.com/spell=70803

Testoval som to dost nez viac inac by som asi nato nedosiel ze to nejde.

**Comment by Dessus** [comment]
Fixed na novy revce
