### ISSUE TITLE
[Quest] Reforging the Sword

### ISSUE THREAD

**Issue by Strepin** [overy/CzechFunCore#58]
Quest http://old.wowhead.com/quest=24559 za boha nejde, Saronite mám, kladivo mám, stojím na kovadlině ale nic se neděje. Opravit, prosím.

**Comment by overy** [comment]
Quest by měl být funkční zkus to na kovadlině o souřadnicích X:727.988, Y:-121.675, Z:515.259 nebo X:661.331, Y:-121.89, Z:514.948 (pomoci prikazu GPS)
