### ISSUE TITLE
[Rogue] - Tricks of the trade

### ISSUE THREAD

**Issue by tukaN-** [overy/CzechFunCore#6]
Nevím jestli jste někdo zkoušel na CZF rogue.. ale zdá se mi, že tricks of the trade (http://www.wowhead.com/spell=57934) nepřidává 15% bonus dmg.

**Comment by Dessus** [comment]
Zdá se ti, nebo to víš? Docela zásadní :D

**Comment by tukaN-** [comment]
No většina lidí říká, že dmg bonus nefunguje.. a když TotTko na někoho nahodím dávám stejné pecky bez rozdílu.

**Comment by overy** [comment]
fixuje další revize
