### ISSUE TITLE
Kaw the Mammoth Destroyer

### ISSUE THREAD

**Issue by FroostiK** [overy/CzechFunCore#60]
V Q Kaw the Mammoth Destroyer se ma zabit Npc s jmenem Kaw the Mammoth Destroyer nefunguje. Důvod je takovyto: spawn je ale nema nastaveno atack target. Proste i kdyz pouzijete spely plosne nezautoci na vas a proto nejde zabit. 
Link na Q je zde http://old.wowhead.com/quest=11879
Prosim o opravu

**Comment by overy** [comment]
precti si komenty na wowheadu zjistis co mas v Questu delat ... 

Venture forth to the plains and find a mammoth bull. He will allow you to mount him and control his movements and actions. Ride upon his back and find Kaw, north of here at Kaw's Roost. Together, you will be the instrument of Kaw's demise.
