### ISSUE TITLE
Halls Of Reflection

### ISSUE THREAD

**Issue by FroostiK** [overy/CzechFunCore#61]
Zdravim
Problem se naskytl v HoR ve spravnem spawnu vln.Takze jak to funguje ted? Ted kdyz zabijite moby v 1 wave a jste pomalejsi tak se vam tam spawne 2wave a porad to pokracuje.
Co vim od kamose z Offi a torchu z netu spravne by to melo byt takto: Prijde 1 wlna i kdyz jste pomalejsi nespavne se 2 wlna dokud neni dead predesla.
Zde je odkaz na cely dung http://www.wowhead.com/zone=4820/halls-of-reflection#drops
Doufam ze se problem vyresi. ;)

**Comment by overy** [comment]
to je kravina ... to mas to same jako ve jako v dungu v dalaranu, taky pokud nestihas tak prijde dalsi vlna ... to same v black morras ... takze i tady to bude stejne, jinak bych nechapal duvod tehle vln kdyz to je tak "easy"
