### ISSUE TITLE
ToCh - mount + 1 boss

### ISSUE THREAD

**Issue by FroostiK** [overy/CzechFunCore#67]
Zdravim  
1) Na horde mounty nejde ubec nasednout http://old.wowhead.com/npc=36558
    Na Ali sice ano ale nemaji spelly http://old.wowhead.com/npc=36557
2) Po prokecu s NPC prijedou zastupci bud hordy nebo alky (Grand Champions + 3 mobove) Mobove jsou friendly a Grand Champions je sice enemy ale nejde zautocit a dmg. Vice tu http://old.wowhead.com/object=195709
Dekuji za opraveni ;)

**Comment by Dessus** [comment]
Fixed na novy revce
