### ISSUE TITLE
Kytky

### ISSUE THREAD

**Issue by martin-ocasek** [overy/CzechFunCore#70]
slabej spawn low lvl kytek .. v pulce durotaru sem nasel nejak 3 kytky coz je proste malo.

**Comment by overy** [comment]
durotar ma 75 spawnu ... jinak prumerne to byva vse nad 50 to mi neprijde jako malo ...

**Comment by martin-ocasek** [comment]
tak nevim jestli sis ty lokace prochazel .. ale v celym durotaru sem nasel tak 15 kytek , ve feralas to stejny v barrens to bylo trosku lepsi ale porad nic moc ..a jako abych po pul hodine hledani kytek jich mel v inventari 20 me prijde na funko fakt malo .. jeste kdyz sou ty raty 15 tak udelat alchemku je na pul dne ..

**Comment by overy** [comment]
no tak asi hledas spatne :X preci jen je to velka lokace ... nastavil jsem durotar a ferelas na 90
