### ISSUE TITLE
[ICC] - Kinetic bomb

### ISSUE THREAD

**Issue by LeetyP** [overy/CzechFunCore#72]
Dostanou dmg, vzletí nahoru ale jejich (neznám ten termín který určuje fyzickou polohu npc / objektu) "duše" se nezvedne, takže není možné nenechat dopadnout bomby. 

Na 10 normal se to dá hrát na equip i když dost blbě (tank kelesetha je odkopnut, ztrácí nucleusy protože je daleko, dostává ik, nazdar)

Na 10 HC vzhledem k debuffu ovlivňující movement je to už téměř nemožné

Na 15 normal se to dá hrát na equip a počet, ale už to vážně není vtipné

Ve všech případech je to prostě docela závažný problém

**Comment by Dessus** [comment]
Fixed po revce
