### ISSUE TITLE
[Shadowfrost Shard] + truhly

### ISSUE THREAD

**Issue by LeetyP** [overy/CzechFunCore#73]
Chybí v truhlách u Valithrie a Deathbringera (asi bude chybět i v gunshipu, ale ten tu nemáme)

http://www.wowhead.com/item=50274#contained-in-object

**Comment by overy** [comment]
muzes mi nejak ve zkratce rict za jakych podminek to ma padat a pod. ?

**Comment by LeetyP** [comment]
Jop jsem zapoměl omlouvám se

Pokud má libovolný člen raidu quest http://www.wowhead.com/quest=24548 je šance na offi 25 až 75% (czf powa plz 100%) že z bosse v citadele na obtížnost 25m nebo 25mHC (nebo truhly ve které je odměna za jeho pokoření) padne jeden tento shard. Shardy korektně padají ze všech soubojů kde je odměna obsažena v "mrtvole" ale v truhlách chybí (DB po smrti spawnuje truhlu, Valithria po záchraně spawnuje truhlu)

**Comment by overy** [comment]
opraveno krom gunshipa ten loot nevede
