### ISSUE TITLE
Junkboxes needed

### ISSUE THREAD

**Issue by Liskulka** [overy/CzechFunCore#80]
NPC Fahrad (frakce ravenholdt, http://www.wowhead.com/npc=57761 ) nenabízí Q Junkbox needed (  http://www.wowhead.com/quest=8249 , nabizi pouze pro rogue, ale ne formou accept, tudiz nejde ani share) Správně má jít pro kohokoliv po získání reputace s ravenholdem, díky za opravu.

**Comment by overy** [comment]
zkus po restartu
