### ISSUE TITLE
chybí questy

### ISSUE THREAD

**Issue by anela** [overy/CzechFunCore#88]
V profesi fishing  [Chasing Marcia] má být celkem 5 denních Q to že jde dát každý den 1 nevadí , ale to že už jsem udělala 3 a dnes se začínají opakovat. tento Q když je celý se zaočítává do Achievements

**Comment by overy** [comment]
není bug, v DB je všech 5 questů a střídají se každý den je jiný ... upozorňuji nemusí se vždy vystřídat všechny, ale třeba jen první 3, pak zas první a pak třeba 5 a pod.
