### ISSUE TITLE
NPC - Dodge

### ISSUE THREAD

**Issue by tukaN-** [overy/CzechFunCore#9]
Nevím jestli se to stává i u jiný mobů, ale při dmgování trashe v ICC se docela často stává, že nestvůry dodgují mé útoky.. přičemž jim stojím vždy v zádech a pro útoky do zad platí: žádný dodge nebo parry. Představte si takového Deathbound warda ( http://www.wowhead.com/npc=37007 ) u které se mi to děje neustále.. Tank nabere warda já si mu stoupnu do zady a začnu ho fackovat.. při takových 2 Mutilatech z 10 pokáždé dodgne.

**Comment by LeetyP** [comment]
Nikoliv, pro PvE útoky zezadu platí JEN A POUZE žádné parry. PvE umí dodgovat i útoky zezadu, proto je třeba expertise

**Comment by Lucr3cia** [comment]
v případě NPC je i parry zezadu avšak o 6% menší než zepředu a proto je třeba mít 26expertise, což je cap potřebný na eliminaci NPC avoidu

**Comment by overy** [comment]
není bug.
